name: 'Build videos using Video Puppet'
description: 'Build videos using Video Puppet'
inputs:
  github-token:
    description: 'Github Authentication Token'
    required: true
  source-path:
    description: 'Relative path to the main video source file (.yaml or .json)'
    required: true
runs:
  using: 'node12'
  main: 'dist/action.js'
