name: 'Build videos using Video Puppet'
description: 'Build videos using Video Puppet'
inputs:
  github-token:
    description: 'Github Authentication Token'
    required: true
  source-path:
    description: 'Relative path to the main video source file (.yaml or .json)'
    required: true
  api-url:
    description: 'Optional override for the API URl'
    required: false  
  result-file:
    description: 'Local file system path for the result file'
    required: false
outputs:
  videoUrl:
    description: 'Temporary video URL - valid for 10 minutes'
  videoFile:
    description: 'Resulting video file, ready for uploading to artifacts or further processing'
runs:
  using: 'node12'
  main: 'dist/action.js'
